# Generated by Django 3.2.16 on 2022-12-02 22:27

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Correo')),
                ('rut', models.DecimalField(decimal_places=0, max_digits=9)),
                ('celular', models.DecimalField(decimal_places=0, max_digits=9)),
                ('username', models.CharField(default='Null', max_length=32)),
                ('intentos', models.IntegerField(default=0)),
                ('is_client', models.BooleanField(default=True, verbose_name='Rol cliente')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Rol admin')),
                ('is_finanza', models.BooleanField(default=False, verbose_name='Rol finanza')),
                ('is_bodega', models.BooleanField(default=False, verbose_name='Rol bodega')),
                ('is_cocina', models.BooleanField(default=False, verbose_name='Rol cocina')),
                ('is_barman', models.BooleanField(default=False, verbose_name='Rol barman')),
                ('is_garzon', models.BooleanField(default=False, verbose_name='Rol garzon')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
