# Generated by Django 3.2.16 on 2022-12-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='Rol cliente'),
        ),
    ]
