# Generated by Django 3.2.16 on 2022-12-04 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_is_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
