# Generated by Django 3.2.16 on 2022-12-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_intentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activo',
        ),
    ]
