# Generated by Django 3.2.16 on 2022-11-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221128_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=12),
        ),
    ]
