# Generated by Django 3.2.16 on 2022-12-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_solicitud', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estado_solicitud',
                'managed': False,
            },
        ),
    ]
